version: '3' 
services:
    mongo:
       image: 'mongo:4.4'
       container_name: tntpMongo
       labels:
            - "name=mongo"
       restart: always
       volumes:
            - tntpMongo:/data/db
       networks:
            - tntpNet
       ports:
        - 27018:27017

networks:
    tntpNet: {}

volumes:
    tntpMongo: